version: "3.8"
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 12345          
        #volumes:
        #- C:/Users/Fabricio/Desktop/MongoDB:/data/mongodb
        ports:
        - 8082:28017
        restart: always
        